import type { Locale } from './i18n';

/**
 * 주요 태그 정의 (튜토리얼 제목 기반)
 * 태그는 튜토리얼의 제목과 설명에서 자동으로 매칭됩니다.
 */
export function getPopularTags(locale: Locale): string[] {
  if (locale === 'en') {
    return [
      'Variables',
      'Operators',
      'Constants',
      'Enum',
      'Functions',
      'Return Values',
      'Parameters',
      'Overloading',
      'Classes',
      'Inheritance',
      'Access Modifiers',
      'Properties',
      'Constructors',
      'Virtual',
      'Interfaces',
      'Delegates',
      'Events',
      'Arrays',
      'Lists',
      'Loops',
      'Dictionary',
      'Unity',
      'Input',
      'Transform',
      'Time',
      'Vector3',
      'GameObject',
      'Mathf',
      'Quaternion',
      'Debug',
      'Mouse',
      'Keyboard',
      'Rotation',
      'Movement',
      'Coordinates',
    ];
  } else {
    return [
      '변수',
      '조건문',
      '연산자',
      '상수',
      'switch',
      'enum',
      '열거형',
      '함수',
      '반환값',
      '매개변수',
      '오버로딩',
      '클래스',
      '상속',
      '접근제한자',
      '프로퍼티',
      '생성자',
      '가상함수',
      '인터페이스',
      '델리게이트',
      '이벤트',
      '배열',
      '리스트',
      '반복문',
      '딕셔너리',
      '유니티',
      'MonoBehaviour',
      'Input',
      'Transform',
      'Time',
      'Vector3',
      'GameObject',
      'Mathf',
      'Quaternion',
      'Debug',
      '마우스',
      '키보드',
      '회전',
      '이동',
      '좌표계',
      '내장함수',
    ];
  }
}

